blank_issues_enabled: false
contact_links:
  - name: Suggest dataset
    url: https://github.com/noaione/vthell-dataset/issues/new?assignees=noaione&labels=suggestion&template=suggest-dataset.md&title=%5BSuggestion%5D+
    about: Please suggest a new dataset here
